export const permissionConstants = {
    GET_PERMISSIONS_REQUEST: 'GET_PERMISSIONS_REQUEST',
    GET_PERMISSIONS_SUCCESS: 'GET_PERMISSIONS_SUCCESS',
    GET_PERMISSIONS_FAILURE: 'GET_PERMISSIONS_FAILURE',

    CREATE_PERMISSION_REQUEST: 'CREATE_PERMISSION_REQUEST',
    CREATE_PERMISSION_SUCCESS: 'CREATE_PERMISSION_SUCCESS',
    CREATE_PERMISSION_FAILURE: 'CREATE_PERMISSION_FAILURE',
    
    DELETE_PERMISSION_REQUEST: 'DELETE_PERMISSION_REQUEST',
    DELETE_PERMISSION_SUCCESS: 'DELETE_PERMISSION_SUCCESS',
    DELETE_PERMISSION_FAILURE: 'DELETE_PERMISSION_FAILURE',

    EDIT_PERMISSION_REQUEST: 'EDIT_PERMISSION_REQUEST',
    EDIT_PERMISSION_SUCCESS: 'EDIT_PERMISSION_SUCCESS',
    EDIT_PERMISSION_FAILURE: 'EDIT_PERMISSION_FAILURE'
};